server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/metamask-auth
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true


